language: groovy
sudo: false
jdk:
 - oraclejdk8
branches:
  only:
  - master
before_install:
 - wget -q https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/ala_common.sh
 - chmod +x ala_common.sh
 - source ./ala_common.sh
 - ala_travis_grails_setup_env
script:
 - ala_travis_grails_build
env:
  global:
  - secure: gB6bScMlQ7l3lR/YuBEla2YCo/y2JN0Dxgq4AJOwOJbK2XNFBz/DgCLnhWnM1LAxm8UjrJ1gk7q2rIkstubx0LD3DQRfDfqFkxZw404HbqQl3g6C7bIa0ReKr7ah8ssfU7+hyLYx3q8s401QVV+S0UJQeCPC60f+K/zOQFG/uhc=
  - secure: SevjG9MNHaw8B9qDsW9TKhbRAeM4RnpRVmUrDuRWBmOVpoX7tlChN4AOzEiknFCkL0ZgD4IUkx5XVylpTRDDxuU6ymEKNdtQOc+Y6GsgBNLGXNA0sEKR/L7Mp6zMlT0/O5p1dxTqaxjRCrv3Br6U4BDsUdhtlSNePBwkwUgx1p4=
